import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Modal from '@/components/Modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stock_app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Modal />
        {children}
      </body>
    </html>
  )
}
